# Generated by Django 2.2.3 on 2019-10-03 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='curves_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectfile',
            name='data_type',
            field=models.CharField(default='float', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectfile',
            name='is_horizontal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
