# Generated by Django 2.2.3 on 2019-10-04 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_auto_20191003_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfile',
            name='completed',
        ),
        migrations.CreateModel(
            name='AnnotatedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='annotated_files', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='annotated_files', to='project.ProjectFile')),
            ],
        ),
    ]
