# Generated by Django 2.2.3 on 2019-10-07 19:18

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20191004_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatedfile',
            name='selected_area',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(upload_to=project.models.project_directory_path),
        ),
    ]
