# Generated by Django 2.2.3 on 2019-11-06 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0005_auto_20191025_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotatedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagged_data', models.TextField()),
                ('selected_area', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='annotated_data', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='annotated_data', to='project.ProjectFile')),
            ],
        ),
    ]
