# Generated by Django 2.2.3 on 2019-11-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_annotateddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='max_annotations',
            field=models.IntegerField(default=3),
        ),
    ]
