# Generated by Django 2.2.3 on 2019-12-18 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_max_annotations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotateddata',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotated_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='annotateddata',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotated_data', to='project.ProjectFile'),
        ),
        migrations.AlterField(
            model_name='annotatedfile',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotated_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='annotatedfile',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotated_files', to='project.ProjectFile'),
        ),
    ]
