# Generated by Django 2.2.3 on 2020-01-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20191218_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectfile',
            old_name='is_horizontal',
            new_name='is_vertical',
        ),
    ]
