# Generated by Django 2.2.3 on 2019-09-11 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_status', models.CharField(choices=[('H', 'HOLD'), ('A', 'ACTIVE'), ('R', 'REMOVED'), ('C', 'CANCELED')], default='H', max_length=1)),
                ('company_role', models.CharField(max_length=256, null=True)),
                ('price_per_annotation', models.FloatField()),
                ('groups', models.ManyToManyField(null=True, related_name='managers', to='project.Group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Annotator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_status', models.CharField(choices=[('H', 'HOLD'), ('A', 'ACTIVE'), ('R', 'REMOVED'), ('C', 'CANCELED')], default='H', max_length=1)),
                ('company_role', models.CharField(max_length=256, null=True)),
                ('projects', models.ManyToManyField(null=True, related_name='annotators', to='project.Project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annotator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
