# Generated by Django 2.2.3 on 2019-09-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256)),
                ('token', models.CharField(max_length=32)),
                ('related_id', models.IntegerField()),
                ('type', models.CharField(choices=[('M', 'MANAGER'), ('A', 'ANNOTATOR')], max_length=1)),
            ],
        ),
    ]
