# Generated by Django 2.2.3 on 2019-09-26 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_inviteduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvitedUser',
        ),
    ]
