# Generated by Django 2.2.3 on 2019-10-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_inviteduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='price_per_annotation',
            field=models.FloatField(default=0),
        ),
    ]
