# Generated by Django 2.2.3 on 2019-12-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191003_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotator',
            name='projects',
            field=models.ManyToManyField(related_name='annotators', to='project.Project'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='groups',
            field=models.ManyToManyField(related_name='managers', to='project.Group'),
        ),
    ]
